name: coba1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^0.13.6
  intl: ^0.20.2
  mysql1: ^0.19.2
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  fl_chart: ^0.66.2
  image_picker: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.2
  animate_do: ^3.0.2
  flutter_local_notifications: ^17.1.0
  flutter_background_service: ^5.0.5
  permission_handler: ^11.3.0
  pdf: ^3.10.4
  printing: ^5.12.0
  excel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
